INSERT INTO region (name) VALUES ('North');
INSERT INTO region (name) VALUES ('Iron Islands');
INSERT INTO region (name) VALUES ('Vale of Arryn');
INSERT INTO region (name) VALUES ('Dorne');
INSERT INTO region (name) VALUES ('Stormlands');
INSERT INTO region (name) VALUES ('Reach');
INSERT INTO region (name) VALUES ('Beyond the Wall');
INSERT INTO region (name) VALUES ('Riverlands');
INSERT INTO region (name) VALUES ('Westerlands');
INSERT INTO region (name) VALUES ('Crownlands');